CREATE TABLE app_state (id INT PRIMARY KEY CHECK (id = 1), version BIGINT NOT NULL);
INSERT INTO app_state (id, version) VALUES (1, 0);

CREATE TABLE import_batch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(16) NOT NULL CHECK (status IN ('STAGED', 'COMMITTED', 'REVERTED')),
  file_name VARCHAR(255) NOT NULL, file_sha256 CHAR(64) NOT NULL, file_size BIGINT NOT NULL,
  row_count INT NOT NULL, window_start DATE NOT NULL, window_end DATE NOT NULL,
  expected_version BIGINT NOT NULL, staged_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL, committed_at TIMESTAMP WITH TIME ZONE,
  reverted_at TIMESTAMP WITH TIME ZONE, CHECK (window_start <= window_end)
);
CREATE TABLE import_batch_account (
  batch_id BIGINT NOT NULL REFERENCES import_batch(id), account VARCHAR(255) NOT NULL,
  PRIMARY KEY (batch_id, account)
);
CREATE TABLE txn (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES import_batch(id), source_line INT NOT NULL, raw_line VARCHAR(8000) NOT NULL,
  account VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, currency CHAR(3) NOT NULL,
  amount DECIMAL(19,4) NOT NULL CHECK (amount >= 0), amount_raw VARCHAR(32) NOT NULL,
  ref_currency_amount DECIMAL(19,4), type VARCHAR(8) NOT NULL CHECK (type IN ('EXPENSE', 'INCOME')),
  type_raw VARCHAR(32) NOT NULL, payment_type VARCHAR(255) NOT NULL, note VARCHAR(1024) NOT NULL,
  payee VARCHAR(255) NOT NULL, labels VARCHAR(1024) NOT NULL,
  occurred_at TIMESTAMP(3) WITH TIME ZONE NOT NULL, occurred_on DATE NOT NULL, transfer BOOLEAN NOT NULL,
  superseded_by_batch BIGINT REFERENCES import_batch(id)
);
CREATE INDEX idx_txn_occurred_on ON txn(occurred_on);
CREATE INDEX idx_txn_account_occurred_on ON txn(account, occurred_on);
CREATE INDEX idx_txn_batch ON txn(batch_id);
CREATE INDEX idx_txn_superseded_by ON txn(superseded_by_batch);
CREATE VIEW active_txn AS
  SELECT t.* FROM txn t JOIN import_batch b ON b.id = t.batch_id
  WHERE b.status = 'COMMITTED' AND t.superseded_by_batch IS NULL;
